"""Optimization report generation: a twenty-section archivable document (Version 32).

Version 33 adds two further sections (21: Algorithm Parameters, 22:
Robust Design) covering population-based algorithm configuration and
uncertainty-aware (robust) design, while leaving the original twenty
sections' numbering and content unchanged.

Extends the Version 30/31 reporting approach to an optimization run.
Lives in :mod:`femtoolkit.optimization` (not
:mod:`femtoolkit.studies`/:mod:`femtoolkit.uncertainty`/
:mod:`femtoolkit.reporting`) to preserve a one-way dependency
direction: optimization (the newest layer) depends on
uncertainty/studies/runs/reporting/verification/validation, never the
reverse. Rendering reuses the same plain-string-formatting, Markdown-
primary/HTML-wrapper approach every prior reporting module in this
toolkit established -- no templating dependency.

This report never claims a global optimum, a guaranteed optimum, or
that an optimized design is unconditionally "better" -- it reports the
baseline, every evaluated candidate, the stopping reason, and the
quantitative difference between the baseline and the best feasible
candidate found, and leaves interpretation to the reader.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Literal

from femtoolkit.exceptions import ValidationError
from femtoolkit.optimization.results import OptimizationResult

ReportFormat = Literal["markdown", "html"]

_STOP_REASON_TEXT = {
    "completed": "The algorithm's own search logic finished (no further improvement found).",
    "max_evaluations": "The configured evaluation budget was reached.",
    "converged": (
        "The best-feasible objective value's relative improvement stayed below the "
        "configured tolerance for the configured number of consecutive evaluations "
        "(an empirically observed plateau, not a proof of global optimality)."
    ),
    "cancelled": (
        "The run was cancelled before finishing; the history up to that point is preserved."
    ),
    "failed": "Too many consecutive evaluations failed in a row.",
    "max_generations": (
        "A population-based algorithm reached its configured generation/iteration budget."
    ),
    "target_reached": (
        "The best-feasible objective value reached the user-supplied target_objective -- "
        "this reflects the configured goal being met, not evidence of a global optimum."
    ),
}

_POPULATION_BASED_ALGORITHMS = (
    "differential_evolution",
    "genetic_algorithm",
    "particle_swarm",
    "nsga2",
)


@dataclass
class OptimizationReport:
    """The complete, rendering-independent content of one optimization report.

    Attributes:
        title: The report title.
        summary: A short, one-paragraph summary of the optimization's purpose.
        base_model_description: A description of the base project every
            design overrode.
        result: The full
            :class:`~femtoolkit.optimization.results.OptimizationResult`
            this report describes.
        plot_paths: File paths to plot images already generated by
            :mod:`femtoolkit.optimization.plots`.
        conclusions: Free text the caller supplies -- never generated
            automatically.
    """

    title: str
    summary: str
    base_model_description: str
    result: OptimizationResult
    plot_paths: list[str] = field(default_factory=list)
    conclusions: str = ""


def build_optimization_report(
    title: str,
    summary: str,
    base_model_description: str,
    result: OptimizationResult,
    plot_paths: list[str] | None = None,
    conclusions: str = "",
) -> OptimizationReport:
    """Build an :class:`OptimizationReport` from an already-completed optimization result."""
    return OptimizationReport(
        title=title,
        summary=summary,
        base_model_description=base_model_description,
        result=result,
        plot_paths=list(plot_paths or []),
        conclusions=conclusions,
    )


def render_optimization_report_markdown(report: OptimizationReport) -> str:
    """Render an :class:`OptimizationReport` as a twenty-section Markdown document.

    Args:
        report: The report to render.

    Returns:
        The complete report as a Markdown string.
    """
    result = report.result
    problem_objectives = result.objectives
    lines: list[str] = [f"# {report.title}", ""]

    lines += ["## 1. Optimization Summary", "", report.summary, ""]
    n_constraints = (
        len(result.history.evaluations[0].constraint_evaluations)
        if result.history.evaluations
        else 0
    )
    objective_kind = "Multi-objective" if result.is_multi_objective else "Single-objective"
    lines += [
        "## 2. Problem Definition",
        "",
        f"Problem: **{result.problem_name}**. {objective_kind} "
        f"({len(problem_objectives)} objective(s), {n_constraints} constraint(s)).",
        "",
    ]

    lines += ["## 3. Baseline Design", ""]
    baseline = result.baseline
    lines.append(f"Status: **{baseline.status.value}**")
    if baseline.design_variables:
        lines.append(f"Variables: {baseline.design_variables}")
    if baseline.objective_values:
        lines.append(f"Objectives: {baseline.objective_values}")
    lines.append("")

    lines += ["## 4. Design Variables", ""]
    lines.append("| Name | Path | Type | Units |")
    lines.append("|---|---|---|---|")
    for variable in result.design_variables:
        lines.append(
            f"| {variable.name} | `{variable.path}` | {variable.variable_type.value} | "
            f"{variable.units or '-'} |"
        )
    lines.append("")

    lines += ["## 5. Bounds", ""]
    lines.append("| Variable | Lower/Categories | Upper | Default |")
    lines.append("|---|---|---|---|")
    for variable in result.design_variables:
        lower = variable.categories if variable.categories is not None else variable.lower_bound
        upper = "-" if variable.categories is not None else variable.upper_bound
        lines.append(f"| {variable.name} | {lower!r} | {upper!r} | {variable.default_value!r} |")
    lines.append("")

    lines += ["## 6. Objectives", ""]
    lines.append("| Name | Direction | Units |")
    lines.append("|---|---|---|")
    for objective in problem_objectives:
        lines.append(
            f"| {objective.name} | {objective.direction.value} | {objective.units or '-'} |"
        )
    lines.append("")

    lines += ["## 7. Constraints", ""]
    if not baseline.constraint_evaluations:
        lines.append("This problem has no constraints.")
    else:
        lines.append("| Name | Relation | Limit | Baseline Value | Baseline Satisfied |")
        lines.append("|---|---|---|---|---|")
        for ce in baseline.constraint_evaluations:
            lines.append(
                f"| {ce.name} | {ce.relation.value} | {ce.limit:.6g} | {ce.value:.6g} | "
                f"{ce.satisfied} |"
            )
    lines.append("")

    lines += ["## 8. Algorithm", "", f"`{result.config.algorithm}`", ""]

    lines += ["## 9. Optimization Configuration", ""]
    config = result.config
    lines.append(f"- **Max evaluations:** {config.max_evaluations}")
    lines.append(f"- **Evaluation limit:** {config.evaluation_limit}")
    lines.append(f"- **Tolerance:** {config.tolerance}")
    lines.append(f"- **Patience:** {config.patience}")
    lines.append(f"- **Seed:** {config.seed}")
    lines.append(f"- **Step size:** {config.step_size}")
    lines.append(f"- **Constraint handling:** {config.constraint_handling}")
    lines.append("")

    lines += ["## 10. Evaluation History", ""]
    lines.append(f"{result.history.n_evaluations} evaluation(s) recorded.")
    lines.append("")
    lines.append("| # | Design ID | Status | Objectives | Violation |")
    lines.append("|---|---|---|---|---|")
    for index, evaluation in enumerate(result.history.evaluations, start=1):
        lines.append(
            f"| {index} | {evaluation.design_id} | {evaluation.status.value} | "
            f"{evaluation.objective_values} | {evaluation.total_violation:.6g} |"
        )
    lines.append("")

    lines += ["## 11. Feasibility Summary", ""]
    lines.append(f"- **Feasible:** {len(result.history.feasible_evaluations())}")
    lines.append(f"- **Infeasible:** {len(result.history.infeasible_evaluations())}")
    lines.append(f"- **Failed/Invalid:** {len(result.history.failed_evaluations())}")
    lines.append("")

    lines += ["## 12. Final Candidate / Non-Dominated Set", ""]
    if result.is_multi_objective:
        front = result.pareto_front()
        if not front:
            lines.append("No feasible design was found; no Pareto front is available.")
        else:
            lines.append(
                f"{len(front)} non-dominated design(s) found. No single design is "
                "identified as \"best\" -- each represents a different trade-off."
            )
            lines.append("")
            lines.append("| Design ID | Objectives |")
            lines.append("|---|---|")
            for evaluation in front:
                lines.append(f"| {evaluation.design_id} | {evaluation.objective_values} |")
    else:
        best = result.best_feasible()
        if best is None:
            lines.append("No feasible design was found during this run.")
        else:
            lines.append(
                f"Best feasible candidate (by {problem_objectives[0].name}, "
                f"{problem_objectives[0].direction.value}): **{best.design_id}**"
            )
            lines.append(f"- Variables: {best.design_variables}")
            lines.append(f"- Objectives: {best.objective_values}")
            improvement = result.improvement_over_baseline()
            if improvement is not None:
                lines.append(
                    f"- Change vs. baseline: {improvement['absolute_difference']:.6e} "
                    f"({improvement['percentage_change']:+.2f}%)"
                )
    lines.append("")

    lines += ["## 13. Objective History", ""]
    lines.append(
        "See the generated objective-history plot(s) (Section 16) for the best-feasible "
        "value trend per objective."
    )
    lines.append("")

    lines += ["## 14. Constraint History", ""]
    lines.append("| # | Total Violation |")
    lines.append("|---|---|")
    for index, evaluation in enumerate(result.history.evaluations, start=1):
        lines.append(f"| {index} | {evaluation.total_violation:.6g} |")
    lines.append("")

    lines += ["## 15. Design Variable History", ""]
    lines.append(
        "See the generated design-variable-history plot(s) (Section 16) for each "
        "variable's trace across every evaluation."
    )
    lines.append("")

    lines += ["## 16. Pareto Front", ""]
    if not result.is_multi_objective:
        lines.append("This is a single-objective problem; no Pareto front applies.")
    elif not report.plot_paths:
        lines.append("No plots were generated for this report.")
    else:
        for path in report.plot_paths:
            lines.append(f"- {path}")
    lines.append("")

    lines += ["## 17. Verification Status", ""]
    verification_counts: dict[str, int] = {}
    for evaluation in result.history.evaluations:
        key = evaluation.verification_status.value
        verification_counts[key] = verification_counts.get(key, 0) + 1
    if not verification_counts:
        lines.append("No evaluations were recorded.")
    else:
        for key, count in sorted(verification_counts.items()):
            lines.append(f"- **{key}:** {count}")
    lines.append("")

    lines += ["## 18. Validation Status", ""]
    lines.append(
        "No reference/experimental dataset was supplied for this optimization run -- "
        "see docs/validation.md for the verification/validation distinction."
    )
    lines.append("")

    lines += ["## 19. Reproducibility Metadata", ""]
    lines.append(f"- **Algorithm:** {config.algorithm}")
    lines.append(f"- **Seed:** {config.seed}")
    lines.append(f"- **Max evaluations:** {config.max_evaluations}")
    lines.append(f"- **Stop reason:** {result.stop_reason.value}")
    lines.append(f"- **Report generated at:** {result.generated_at}")
    lines.append("")

    lines += ["## 20. Limitations", ""]
    stop_reason_text = _STOP_REASON_TEXT[result.stop_reason.value]
    lines.append(f"Stop reason: **{result.stop_reason.value}** -- {stop_reason_text}")
    lines.append("")
    lines.append(
        "This report never claims a global, guaranteed, or mathematically optimal "
        "design. Random search and coordinate search are both derivative-free "
        "heuristics with no convergence guarantee; coordinate search in particular "
        "can stop at a local optimum. Every reported improvement is a quantitative "
        "comparison to the baseline only, never a claim of unconditional superiority. "
        "No distributed/parallel/GPU optimization is implemented in this version -- "
        "every evaluation ran sequentially."
    )
    lines.append("")

    lines += ["## 21. Algorithm Parameters", ""]
    if config.algorithm in _POPULATION_BASED_ALGORITHMS:
        lines.append(f"- **Population size:** {config.population_size}")
        lines.append(f"- **Max generations:** {config.max_generations}")
        if config.algorithm == "differential_evolution":
            lines.append(f"- **Mutation factor (F):** {config.mutation_factor}")
            lines.append(f"- **Crossover probability (CR):** {config.crossover_probability}")
        if config.algorithm in ("genetic_algorithm", "nsga2"):
            lines.append(f"- **Crossover probability:** {config.crossover_probability}")
            lines.append(f"- **Mutation probability:** {config.mutation_probability}")
            lines.append(f"- **Tournament size:** {config.tournament_size}")
        if config.algorithm == "genetic_algorithm":
            lines.append(f"- **Elite count:** {config.elite_count}")
        if config.algorithm == "particle_swarm":
            lines.append(f"- **Inertia weight (w):** {config.inertia_weight}")
            lines.append(f"- **Cognitive coefficient (c1):** {config.cognitive_coefficient}")
            lines.append(f"- **Social coefficient (c2):** {config.social_coefficient}")
            lines.append(f"- **Velocity limit:** {config.velocity_limit}")
        n_generations = len(
            {e.generation for e in result.history.evaluations if e.generation is not None}
        )
        lines.append(f"- **Generations actually run:** {n_generations}")
    else:
        lines.append(
            f"Not applicable -- `{config.algorithm}` has no population/generation "
            "parameters."
        )
    lines.append(f"- **Termination reason:** {result.stop_reason.value}")
    lines.append("")

    lines += ["## 22. Robust Design", ""]
    robust_config = result.robust_config
    if robust_config is None or not robust_config.uncertainty_enabled:
        lines.append("Robust (uncertainty-aware) design was not used for this optimization run.")
    else:
        lines.append(f"- **Sampling method:** {robust_config.sampling_method}")
        lines.append(f"- **Sample count per design:** {robust_config.sample_count}")
        lines.append(f"- **Random seed:** {robust_config.random_seed}")
        lines.append(f"- **Objective statistic:** {robust_config.objective_statistic}")
        lines.append(f"- **Constraint statistic:** {robust_config.constraint_statistic}")
        lines.append(f"- **Percentile (if used):** {robust_config.percentile}")
        lines.append(f"- **Failure policy:** {robust_config.failure_policy}")
        lines.append(
            f"- **Maximum total FEA evaluations:** {robust_config.maximum_total_evaluations}"
        )
        lines.append(
            "- **Note:** every statistic here is an empirical estimate from a finite "
            "Monte Carlo sample at one design point -- never a rigorous reliability "
            "index (no FORM/SORM is implemented)."
        )
        best = result.best_feasible() if not result.is_multi_objective else None
        if best is not None and best.metadata:
            if "robust_objectives" in best.metadata:
                lines.append("")
                lines.append("Best feasible candidate's robust objective diagnostics:")
                for quantity, info in best.metadata["robust_objectives"].items():
                    lines.append(
                        f"  - {quantity}: {info['statistic']}={info['value']:.6g} "
                        f"(n_samples={info['n_samples']})"
                    )
            if "robust_constraints" in best.metadata:
                lines.append("Best feasible candidate's robust constraint diagnostics:")
                for quantity, info in best.metadata["robust_constraints"].items():
                    lines.append(
                        f"  - {quantity}: {info['statistic']}={info['value']:.6g} "
                        f"(n_samples={info['n_samples']})"
                    )
    lines.append("")

    if report.conclusions:
        lines.append(report.conclusions)
        lines.append("")

    return "\n".join(lines)


def render_optimization_report_html(report: OptimizationReport) -> str:
    """Render an :class:`OptimizationReport` as a minimal, self-contained HTML document.

    Args:
        report: The report to render.

    Returns:
        The complete report as an HTML string.
    """
    import html as html_module

    markdown_text = render_optimization_report_markdown(report)
    escaped_lines = [html_module.escape(line) for line in markdown_text.split("\n")]
    body = "\n".join(f"<p>{line}</p>" if line else "<br/>" for line in escaped_lines)
    return (
        '<!DOCTYPE html>\n<html><head><meta charset="utf-8">'
        f"<title>{html_module.escape(report.title)}</title></head>"
        f"<body>{body}</body></html>"
    )


def save_optimization_report(
    report: OptimizationReport, path: str | Path, report_format: ReportFormat
) -> None:
    """Render and write an :class:`OptimizationReport` to a file.

    Args:
        report: The report to render.
        path: Output file path.
        report_format: ``"markdown"`` or ``"html"``.

    Raises:
        ValidationError: If ``report_format`` is not supported.
    """
    if report_format == "markdown":
        text = render_optimization_report_markdown(report)
    elif report_format == "html":
        text = render_optimization_report_html(report)
    else:
        raise ValidationError(
            f"Unsupported report_format {report_format!r}, expected 'markdown' or 'html'."
        )
    Path(path).write_text(text)


__all__ = [
    "OptimizationReport",
    "ReportFormat",
    "build_optimization_report",
    "render_optimization_report_html",
    "render_optimization_report_markdown",
    "save_optimization_report",
]
