"""Uncertainty report generation: a nineteen-section archivable document (Version 31).

Extends the Version 30 study-reporting approach
(:mod:`femtoolkit.studies.report`) to a Monte Carlo uncertainty study.
Lives in :mod:`femtoolkit.uncertainty` (not
:mod:`femtoolkit.studies`/:mod:`femtoolkit.reporting`) to preserve a
one-way dependency direction: uncertainty (the newest layer) depends on
studies/runs/reporting/verification/validation, never the reverse.
Rendering reuses the same plain-string-formatting, Markdown-primary/
HTML-wrapper approach every prior reporting module in this toolkit
established -- no templating dependency.

This report clearly separates what was *observed* in this specific
Monte Carlo sample (output statistics, percentiles) from what was
*estimated with a stated uncertainty of its own* (confidence intervals
for the mean, the empirical exceedance frequency) -- see each section's
introductory text in the rendered output.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import TYPE_CHECKING, Literal

from femtoolkit.exceptions import ValidationError
from femtoolkit.uncertainty.monte_carlo import MonteCarloResult

if TYPE_CHECKING:
    from femtoolkit.reporting.metadata import ReproducibilityMetadata
    from femtoolkit.studies.sensitivity import SensitivityResult
    from femtoolkit.uncertainty.confidence import ConfidenceInterval
    from femtoolkit.uncertainty.correlation import CorrelationResult
    from femtoolkit.uncertainty.reliability import ExceedanceResult
    from femtoolkit.uncertainty.statistics import OutputStatistics

ReportFormat = Literal["markdown", "html"]


@dataclass
class UncertaintyReport:
    """The complete, rendering-independent content of one uncertainty-analysis report.

    Attributes:
        title: The report title.
        study_summary: A short, one-paragraph summary of the study's purpose.
        base_model_description: A description of the base project the study varied.
        result: The full :class:`~femtoolkit.uncertainty.monte_carlo.MonteCarloResult`
            this report describes.
        output_statistics: Descriptive statistics per output quantity,
            already computed by the caller.
        confidence_intervals: Estimated-mean confidence intervals per
            output quantity, already computed by the caller.
        correlations: Input/output correlation results, already
            computed by the caller.
        exceedances: Limit-exceedance results, already computed by the caller.
        local_sensitivities: Optional Version 30 local finite-difference
            sensitivity results, for contrast with this study's global
            correlation-based sensitivity.
        plot_paths: File paths to plot images already generated by
            :mod:`femtoolkit.uncertainty.plots`.
        conclusions: Free text the caller supplies -- never generated
            automatically.
    """

    title: str
    study_summary: str
    base_model_description: str
    result: MonteCarloResult
    output_statistics: list[OutputStatistics] = field(default_factory=list)
    confidence_intervals: list[ConfidenceInterval] = field(default_factory=list)
    correlations: list[CorrelationResult] = field(default_factory=list)
    exceedances: list[ExceedanceResult] = field(default_factory=list)
    local_sensitivities: list[SensitivityResult] = field(default_factory=list)
    plot_paths: list[str] = field(default_factory=list)
    conclusions: str = ""


def build_uncertainty_report(
    title: str,
    study_summary: str,
    base_model_description: str,
    result: MonteCarloResult,
    output_statistics: list[OutputStatistics] | None = None,
    confidence_intervals: list[ConfidenceInterval] | None = None,
    correlations: list[CorrelationResult] | None = None,
    exceedances: list[ExceedanceResult] | None = None,
    local_sensitivities: list[SensitivityResult] | None = None,
    plot_paths: list[str] | None = None,
    conclusions: str = "",
) -> UncertaintyReport:
    """Build an :class:`UncertaintyReport` from already-computed analysis pieces.

    This function performs no statistical computation itself -- every
    argument is data the caller already produced with
    :mod:`femtoolkit.uncertainty.statistics`/``confidence``/
    ``correlation``/``reliability``.
    """
    return UncertaintyReport(
        title=title,
        study_summary=study_summary,
        base_model_description=base_model_description,
        result=result,
        output_statistics=list(output_statistics or []),
        confidence_intervals=list(confidence_intervals or []),
        correlations=list(correlations or []),
        exceedances=list(exceedances or []),
        local_sensitivities=list(local_sensitivities or []),
        plot_paths=list(plot_paths or []),
        conclusions=conclusions,
    )


def _reproducibility_metadata(result: MonteCarloResult) -> ReproducibilityMetadata | None:
    if result.study_result.successful_runs:
        return result.study_result.successful_runs[0].reproducibility_metadata
    return None


def render_uncertainty_report_markdown(report: UncertaintyReport) -> str:
    """Render an :class:`UncertaintyReport` as a nineteen-section Markdown document.

    Args:
        report: The report to render.

    Returns:
        The complete report as a Markdown string.
    """
    result = report.result
    config = result.config
    lines: list[str] = [f"# {report.title}", ""]

    lines += ["## 1. Study Summary", "", report.study_summary, ""]
    lines += ["## 2. Base Model", "", report.base_model_description, ""]

    lines += ["## 3. Uncertain Parameters", ""]
    lines.append("| Parameter | Path | Category | Units | Physical Bounds |")
    lines.append("|---|---|---|---|---|")
    for parameter in config.parameters:
        lines.append(
            f"| {parameter.label} | `{parameter.path}` | {parameter.category.value} | "
            f"{parameter.units or '-'} | {parameter.effective_bounds()} |"
        )
    lines.append("")

    lines += ["## 4. Probability Distributions", ""]
    lines.append("| Parameter | Distribution | Mean | Std |")
    lines.append("|---|---|---|---|")
    for parameter in config.parameters:
        distribution = parameter.distribution
        lines.append(
            f"| {parameter.label} | {type(distribution).__name__} | "
            f"{distribution.mean():.6g} | {distribution.std():.6g} |"
        )
    lines.append("")

    lines += ["## 5. Sampling Method", "", f"`{config.method}`", ""]
    lines += ["## 6. Sample Count", "", f"Requested: {config.n_samples}", ""]
    lines += [
        "## 7. Random Seed",
        "",
        f"`{config.seed}`" if config.seed is not None else "Not set (non-reproducible).",
        "",
    ]

    lines += ["## 8. Simulation Run Statistics", ""]
    lines.append(
        f"- **Successful:** {result.n_successful}\n"
        f"- **Failed:** {result.n_failed}\n"
        f"- **Rejected as physically invalid before execution:** {result.n_invalid}\n"
        f"- **Total requested:** {config.n_samples}"
    )
    lines.append("")

    lines += ["## 9. Output Statistics", ""]
    if not report.output_statistics:
        lines.append("No output statistics were computed for this report.")
    else:
        lines.append("| Quantity | N | Mean | Std | CV | Min | Max |")
        lines.append("|---|---|---|---|---|---|---|")
        for stats in report.output_statistics:
            mean_text = "-" if stats.mean is None else f"{stats.mean:.6e}"
            std_text = "-" if stats.std is None else f"{stats.std:.6e}"
            cv_text = (
                "-"
                if stats.coefficient_of_variation is None
                else f"{stats.coefficient_of_variation:.4f}"
            )
            min_text = "-" if stats.minimum is None else f"{stats.minimum:.6e}"
            max_text = "-" if stats.maximum is None else f"{stats.maximum:.6e}"
            lines.append(
                f"| {stats.quantity_label} | {stats.n_successful} | {mean_text} | {std_text} | "
                f"{cv_text} | {min_text} | {max_text} |"
            )
    lines.append("")

    lines += ["## 10. Percentiles", ""]
    lines.append(
        "Percentiles describe the *sampled output distribution itself* -- not a confidence "
        "interval on any estimated statistic (see Section 11)."
    )
    lines.append("")
    for stats in report.output_statistics:
        if not stats.percentiles:
            continue
        lines.append(f"**{stats.quantity_label}**")
        lines.append("")
        lines.append("| Percentile | Value |")
        lines.append("|---|---|")
        for percentile, value in sorted(stats.percentiles.items()):
            lines.append(f"| P{percentile:g} | {value:.6e} |")
        lines.append("")

    lines += ["## 11. Confidence Intervals", ""]
    if not report.confidence_intervals:
        lines.append("No confidence interval was computed for this report.")
    else:
        lines.append(
            "A confidence interval for the *estimated mean* -- not a percentile of the output "
            "distribution (Student-t interval, see docs/uncertainty.md)."
        )
        lines.append("")
        lines.append("| Quantity | Confidence | Mean | Lower | Upper | N |")
        lines.append("|---|---|---|---|---|---|")
        for ci in report.confidence_intervals:
            lines.append(
                f"| {ci.quantity_label} | {ci.confidence_level:.0%} | {ci.mean:.6e} | "
                f"{ci.lower:.6e} | {ci.upper:.6e} | {ci.n_samples} |"
            )
    lines.append("")

    lines += ["## 12. Correlation Analysis", ""]
    if not report.correlations:
        lines.append("No correlation analysis was computed for this report.")
    else:
        lines.append(
            "Descriptive association only -- correlation does not imply causation, and "
            "Pearson's r primarily measures linear association (see docs/uncertainty.md)."
        )
        lines.append("")
        lines.append("| Parameter | Quantity | Pearson r | Spearman rho | N |")
        lines.append("|---|---|---|---|---|")
        for correlation in report.correlations:
            spearman_text = (
                "-" if correlation.spearman_rho is None else f"{correlation.spearman_rho:.4f}"
            )
            lines.append(
                f"| {correlation.parameter_label} | {correlation.quantity_label} | "
                f"{correlation.pearson_r:.4f} | {spearman_text} | {correlation.n_samples} |"
            )
    lines.append("")

    lines += ["## 13. Limit Exceedance", ""]
    if not report.exceedances:
        lines.append("No limit exceedance was evaluated for this report.")
    else:
        lines.append(
            "An empirical frequency from this Monte Carlo sample -- not a rigorous "
            "reliability index (see docs/uncertainty.md)."
        )
        lines.append("")
        lines.append("| Quantity | Threshold | Direction | N Exceeding | N | Frequency |")
        lines.append("|---|---|---|---|---|---|")
        for exceedance in report.exceedances:
            lines.append(
                f"| {exceedance.quantity_label} | {exceedance.threshold:.6g} | "
                f"{exceedance.direction} | {exceedance.n_exceeding} | {exceedance.n_samples} | "
                f"{exceedance.exceedance_frequency:.2%} |"
            )
    lines.append("")

    lines += ["## 14. Histograms", ""]
    if not report.plot_paths:
        lines.append("No plots were generated for this report.")
    else:
        for path in report.plot_paths:
            lines.append(f"- {path}")
    lines.append("")

    lines += ["## 15. Sensitivity Information", ""]
    if not report.local_sensitivities:
        lines.append(
            "No local (Version 30 finite-difference) sensitivity was computed for this "
            "report; see Section 12 for this study's global, sample-based sensitivity."
        )
    else:
        lines.append(
            "Local finite-difference sensitivity around a nominal point (Version 30), for "
            "contrast with Section 12's global, sample-based correlation."
        )
        lines.append("")
        lines.append("| Parameter | Quantity | p1 | p2 | S |")
        lines.append("|---|---|---|---|---|")
        for entry in report.local_sensitivities:
            lines.append(
                f"| {entry.parameter_label} | {entry.quantity_label} | {entry.p1:.6g} | "
                f"{entry.p2:.6g} | {entry.sensitivity:.6g} |"
            )
    lines.append("")

    lines += ["## 16. Verification Status", ""]
    verification_summary = result.study_result.verification_summary()
    if not verification_summary:
        lines.append("No runs were executed.")
    else:
        for status_value, count in sorted(verification_summary.items()):
            lines.append(f"- **{status_value}:** {count}")
    lines.append("")

    lines += ["## 17. Validation Status", ""]
    validation_summary = result.study_result.validation_summary()
    for status_value, count in sorted(validation_summary.items()):
        lines.append(f"- **{status_value}:** {count}")
    lines.append("")

    lines += ["## 18. Reproducibility Metadata", ""]
    metadata = _reproducibility_metadata(result)
    if metadata is None:
        lines.append("No run completed successfully, so no reproducibility metadata is available.")
    else:
        lines.append(f"- **Toolkit version:** {metadata.toolkit_version}")
        lines.append(f"- **Python version:** {metadata.python_version}")
        lines.append(f"- **Sampling method:** {config.method}")
        lines.append(f"- **Random seed:** {config.seed}")
        lines.append(f"- **Sample count:** {config.n_samples}")
        lines.append(f"- **Report generated at:** {result.generated_at}")
    lines.append("")

    lines += ["## 19. Limitations", ""]
    lines.append(
        "Statistical estimates in this report (mean, confidence intervals, correlation, "
        "exceedance frequency) are subject to Monte Carlo sampling error, which shrinks "
        "only slowly as the sample count grows. Percentiles describe this specific sample, "
        "not a rigorously bounded population quantile. Exceedance frequencies are empirical, "
        "not a formal reliability index (no FORM/SORM or importance sampling is implemented). "
        "Correlation is a linear/monotonic association measure, not proof of physical "
        "causality. Floating-point results may vary slightly across software/hardware "
        "environments even with an identical seed."
    )
    lines.append("")

    if report.conclusions:
        lines.append(report.conclusions)
        lines.append("")

    return "\n".join(lines)


def render_uncertainty_report_html(report: UncertaintyReport) -> str:
    """Render an :class:`UncertaintyReport` as a minimal, self-contained HTML document.

    Args:
        report: The report to render.

    Returns:
        The complete report as an HTML string.
    """
    import html as html_module

    markdown_text = render_uncertainty_report_markdown(report)
    escaped_lines = [html_module.escape(line) for line in markdown_text.split("\n")]
    body = "\n".join(f"<p>{line}</p>" if line else "<br/>" for line in escaped_lines)
    return (
        '<!DOCTYPE html>\n<html><head><meta charset="utf-8">'
        f"<title>{html_module.escape(report.title)}</title></head>"
        f"<body>{body}</body></html>"
    )


def save_uncertainty_report(
    report: UncertaintyReport, path: str | Path, report_format: ReportFormat
) -> None:
    """Render and write an :class:`UncertaintyReport` to a file.

    Args:
        report: The report to render.
        path: Output file path.
        report_format: ``"markdown"`` or ``"html"``.

    Raises:
        ValidationError: If ``report_format`` is not supported.
    """
    if report_format == "markdown":
        text = render_uncertainty_report_markdown(report)
    elif report_format == "html":
        text = render_uncertainty_report_html(report)
    else:
        raise ValidationError(
            f"Unsupported report_format {report_format!r}, expected 'markdown' or 'html'."
        )
    Path(path).write_text(text)


__all__ = [
    "ReportFormat",
    "UncertaintyReport",
    "build_uncertainty_report",
    "render_uncertainty_report_html",
    "render_uncertainty_report_markdown",
    "save_uncertainty_report",
]
