"""Study report generation: a thirteen-section archivable study document (Version 30).

Extends the Version 29 engineering-reporting approach
(:mod:`femtoolkit.reporting`) to a parameter study: rather than one
simulation's results, a study report summarizes every scenario, every
run's status, the aggregated verification/validation picture, the
result comparisons and sensitivities a caller computed, and the
reproducibility metadata needed to reproduce it.

This lives in :mod:`femtoolkit.studies` rather than
:mod:`femtoolkit.reporting` to keep the dependency direction one-way:
studies (the newest, highest layer) depends on reporting/verification/
validation/application, never the reverse -- see
``src/femtoolkit/studies/__init__.py``'s module docstring. Rendering
reuses the exact plain-string-formatting, Markdown-primary/HTML-wrapper
approach :mod:`femtoolkit.reporting.renderers` established -- no new
templating dependency.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import TYPE_CHECKING, Literal

from femtoolkit.exceptions import ValidationError
from femtoolkit.studies.results import StudyResult
from femtoolkit.verification.status import VerificationStatus

if TYPE_CHECKING:
    from femtoolkit.reporting.metadata import ReproducibilityMetadata
    from femtoolkit.studies.comparison import ComparisonResult
    from femtoolkit.studies.sensitivity import SensitivityResult

ReportFormat = Literal["markdown", "html"]

_STATUS_MARKER = {
    VerificationStatus.PASS: "PASS",
    VerificationStatus.FAIL: "FAIL",
    VerificationStatus.WARNING: "WARNING",
    VerificationStatus.NOT_AVAILABLE: "NOT AVAILABLE",
    VerificationStatus.NOT_RUN: "NOT RUN",
}


@dataclass
class StudyReport:
    """The complete, rendering-independent content of one study report.

    Attributes:
        title: The report title.
        study_summary: A short, one-paragraph summary of the study's
            purpose.
        base_model_description: A description of the base project the
            study varied.
        result: The full :class:`~femtoolkit.studies.results.StudyResult`
            this report describes -- provides the parameter
            definitions, scenarios, run status, and verification/
            validation summaries directly, without duplicating them
            onto this dataclass.
        comparisons: Every result comparison the caller computed (via
            :meth:`~femtoolkit.studies.results.StudyResult.compare`),
            included as-is -- this report never computes its own
            comparison.
        sensitivities: Every sensitivity series the caller computed
            (via :meth:`~femtoolkit.studies.results.StudyResult.sensitivity`).
        plot_paths: File paths to plot images already generated by
            :mod:`femtoolkit.studies.plots` -- referenced by path, never
            re-generated or embedded by this module.
        reproducibility: Reproducibility metadata representative of the
            study (typically taken from the first successful run), or
            ``None`` if no run completed successfully.
        conclusions: Free text the caller supplies -- never generated
            automatically, matching the Version 29 reporting principle.
    """

    title: str
    study_summary: str
    base_model_description: str
    result: StudyResult
    comparisons: list[ComparisonResult] = field(default_factory=list)
    sensitivities: list[list[SensitivityResult]] = field(default_factory=list)
    plot_paths: list[str] = field(default_factory=list)
    reproducibility: ReproducibilityMetadata | None = None
    conclusions: str = ""


def build_study_report(
    title: str,
    study_summary: str,
    base_model_description: str,
    result: StudyResult,
    comparisons: list[ComparisonResult] | None = None,
    sensitivities: list[list[SensitivityResult]] | None = None,
    plot_paths: list[str] | None = None,
    conclusions: str = "",
) -> StudyReport:
    """Build a :class:`StudyReport`, filling reproducibility metadata from the first successful run.

    Args:
        title: The report title.
        study_summary: A short summary of the study's purpose.
        base_model_description: A description of the base model.
        result: The study's collected :class:`~femtoolkit.studies.results.StudyResult`.
        comparisons: Result comparisons already computed by the caller.
        sensitivities: Sensitivity series already computed by the
            caller.
        plot_paths: Paths to plot images already generated.
        conclusions: Free-text conclusions.

    Returns:
        A populated :class:`StudyReport`.
    """
    reproducibility = None
    if result.successful_runs:
        reproducibility = result.successful_runs[0].reproducibility_metadata

    return StudyReport(
        title=title,
        study_summary=study_summary,
        base_model_description=base_model_description,
        result=result,
        comparisons=list(comparisons or []),
        sensitivities=list(sensitivities or []),
        plot_paths=list(plot_paths or []),
        reproducibility=reproducibility,
        conclusions=conclusions,
    )


def render_study_report_markdown(report: StudyReport) -> str:
    """Render a :class:`StudyReport` as a thirteen-section Markdown document.

    Args:
        report: The report to render.

    Returns:
        The complete report as a Markdown string.
    """
    result = report.result
    lines: list[str] = [f"# {report.title}", ""]

    lines += ["## 1. Study Summary", "", report.study_summary, ""]
    lines += ["## 2. Base Model", "", report.base_model_description, ""]

    lines += ["## 3. Parameter Definitions", ""]
    if not result.parameters:
        lines.append("This study was defined entirely by explicit scenarios (no swept parameters).")
    else:
        lines.append("| Parameter | Path | Values |")
        lines.append("|---|---|---|")
        for parameter in result.parameters:
            values_text = ", ".join(repr(value) for value in parameter.values)
            lines.append(f"| {parameter.label} | `{parameter.path}` | {values_text} |")
    lines.append("")

    lines += ["## 4. Scenarios", ""]
    lines.append(f"{len(result.scenarios)} scenario(s) executed.")
    lines.append("")
    lines.append("| Scenario ID | Name | Description |")
    lines.append("|---|---|---|")
    for scenario in result.scenarios:
        lines.append(f"| {scenario.scenario_id} | {scenario.name} | {scenario.description} |")
    lines.append("")

    lines += ["## 5. Run Status", ""]
    lines.append(
        f"{len(result.successful_runs)} succeeded, {len(result.failed_runs)} failed, "
        f"{len(result.runs)} total."
    )
    lines.append("")
    lines.append("| Run ID | Scenario ID | Status | Execution Time (s) |")
    lines.append("|---|---|---|---|")
    for run in result.runs:
        time_text = (
            "-" if run.execution_time_seconds is None else f"{run.execution_time_seconds:.4f}"
        )
        lines.append(
            f"| {run.run_id} | {run.scenario_id or '-'} | {run.status.value} | {time_text} |"
        )
    lines.append("")

    lines += ["## 6. Solver Information", ""]
    if not result.successful_runs:
        lines.append("No run completed successfully, so no solver diagnostics are available.")
    else:
        solver_names = {
            run.result.solver_diagnostics.solver_name
            for run in result.successful_runs
            if run.result is not None and run.result.solver_diagnostics is not None
        }
        if solver_names:
            lines.append(f"Solver(s) used: {', '.join(sorted(solver_names))}.")
        else:
            lines.append("Default dense direct solve (no per-run solver diagnostics recorded).")
    lines.append("")

    lines += ["## 7. Verification Summary", ""]
    verification_summary = result.verification_summary()
    if not verification_summary:
        lines.append("No runs were executed.")
    else:
        for status_value, count in sorted(verification_summary.items()):
            lines.append(f"- **{status_value}:** {count}")
    lines.append("")

    lines += ["## 8. Validation Summary", ""]
    validation_summary = result.validation_summary()
    for status_value, count in sorted(validation_summary.items()):
        lines.append(f"- **{status_value}:** {count}")
    lines.append(
        "A validated result requires a real reference dataset explicitly supplied by the "
        "caller -- see docs/validation.md. Studies with no reference dataset are reported as "
        "'not_validated', never assumed valid."
    )
    lines.append("")

    lines += ["## 9. Result Comparison", ""]
    if not report.comparisons:
        lines.append("No result comparison was computed for this report.")
    else:
        for comparison in report.comparisons:
            lines.append(f"### {comparison.quantity_label}")
            lines.append("")
            lines.append("| Run 1 | Run 2 | Value 1 | Value 2 | Abs. Diff | Rel. Diff | % Change |")
            lines.append("|---|---|---|---|---|---|---|")
            for entry in comparison.entries:
                lines.append(
                    f"| {entry.run_id_1} | {entry.run_id_2} | {entry.value1:.6e} | "
                    f"{entry.value2:.6e} | {entry.absolute_difference:.6e} | "
                    f"{entry.relative_difference:.4f} | {entry.percentage_change:.2f}% |"
                )
            lines.append("")

    lines += ["## 10. Sensitivity Results", ""]
    if not report.sensitivities:
        lines.append("No sensitivity analysis was computed for this report.")
    else:
        for series in report.sensitivities:
            if not series:
                continue
            first = series[0]
            lines.append(f"### {first.quantity_label} vs. {first.parameter_label}")
            lines.append("")
            lines.append("| p1 | p2 | y1 | y2 | Sensitivity S |")
            lines.append("|---|---|---|---|---|")
            for entry in series:
                lines.append(
                    f"| {entry.p1:.6g} | {entry.p2:.6g} | {entry.y1:.6e} | {entry.y2:.6e} | "
                    f"{entry.sensitivity:.6g} |"
                )
            lines.append("")

    lines += ["## 11. Plots", ""]
    if not report.plot_paths:
        lines.append("No plots were generated for this report.")
    else:
        for path in report.plot_paths:
            lines.append(f"- {path}")
    lines.append("")

    lines += ["## 12. Failed Runs", ""]
    if not result.failed_runs:
        lines.append("No runs failed.")
    else:
        lines.append("| Run ID | Scenario ID | Stage | Error |")
        lines.append("|---|---|---|---|")
        for run in result.failed_runs:
            lines.append(
                f"| {run.run_id} | {run.scenario_id or '-'} | {run.error_stage or '-'} | "
                f"{run.error_message or '-'} |"
            )
    lines.append("")

    lines += ["## 13. Reproducibility Metadata", ""]
    metadata = report.reproducibility
    if metadata is None:
        lines.append("No run completed successfully, so no reproducibility metadata is available.")
    else:
        lines.append(f"- **Toolkit version:** {metadata.toolkit_version}")
        lines.append(f"- **Python version:** {metadata.python_version}")
        lines.append(f"- **Platform:** {metadata.platform_description}")
        dependency_text = ", ".join(
            f"{name}={version}" for name, version in metadata.dependency_versions.items()
        )
        lines.append(f"- **Dependencies:** {dependency_text or 'none recorded'}")
        lines.append(f"- **Generated at:** {metadata.generated_at}")
    lines.append("")

    if report.conclusions:
        lines.append(report.conclusions)
        lines.append("")

    return "\n".join(lines)


def render_study_report_html(report: StudyReport) -> str:
    """Render a :class:`StudyReport` as a minimal, self-contained HTML document.

    Args:
        report: The report to render.

    Returns:
        The complete report as an HTML string.
    """
    import html as html_module

    markdown_text = render_study_report_markdown(report)
    escaped_lines = [html_module.escape(line) for line in markdown_text.split("\n")]
    body = "\n".join(f"<p>{line}</p>" if line else "<br/>" for line in escaped_lines)
    return (
        '<!DOCTYPE html>\n<html><head><meta charset="utf-8">'
        f"<title>{html_module.escape(report.title)}</title></head>"
        f"<body>{body}</body></html>"
    )


def save_study_report(report: StudyReport, path: str | Path, report_format: ReportFormat) -> None:
    """Render and write a :class:`StudyReport` to a file.

    Args:
        report: The report to render.
        path: Output file path.
        report_format: ``"markdown"`` or ``"html"``.

    Raises:
        ValidationError: If ``report_format`` is not supported.
    """
    if report_format == "markdown":
        text = render_study_report_markdown(report)
    elif report_format == "html":
        text = render_study_report_html(report)
    else:
        raise ValidationError(
            f"Unsupported report_format {report_format!r}, expected 'markdown' or 'html'."
        )
    Path(path).write_text(text)


__all__ = [
    "ReportFormat",
    "StudyReport",
    "build_study_report",
    "render_study_report_html",
    "render_study_report_markdown",
    "save_study_report",
]
