"""`SimulationStudy` and `StudyRunner`: orchestrating a parameter study (Version 30).

**Engineering concept.** A *simulation study* is a complete parameter
investigation: a base model, a set of scenarios (explicit and/or
generated by a parameter sweep), and every run those scenarios produce.
:class:`StudyRunner` performs the generate -> validate -> execute ->
collect stages; comparison, sensitivity, and summarization are then
composed from the collected :class:`~femtoolkit.studies.results.StudyResult`
(see its ``compare``/``sensitivity``/``verification_summary``/
``validation_summary`` methods) rather than being folded into the
runner itself -- which quantity to compare or which parameter to run a
sensitivity against is a caller decision this runner has no way to
guess safely across every analysis type.

**Execution is sequential by design.** Each scenario's project is built
and solved one at a time, in order, via
:meth:`~femtoolkit.runs.manager.SimulationRunManager.execute` -- no
parallel or distributed execution is implemented in this version. The
loop is structured as a plain, independent per-scenario step precisely
so a future version can swap it for the Version 27 parallel execution
infrastructure without changing anything about scenario generation,
validation, or result collection.
"""

from __future__ import annotations

from dataclasses import dataclass, field

from femtoolkit.application.project import Project
from femtoolkit.exceptions import StudySizeExceededError
from femtoolkit.runs.manager import SimulationRunManager
from femtoolkit.studies.parameter_sweep import DEFAULT_MAX_SCENARIOS, ParameterDefinition
from femtoolkit.studies.parameter_sweep import generate_scenarios as _generate_scenarios
from femtoolkit.studies.results import StudyResult
from femtoolkit.studies.scenarios import Scenario, apply_scenario, validate_unique_scenario_ids


@dataclass
class SimulationStudy:
    """The definition of one parameter study, before it is run.

    Attributes:
        study_id: A unique identifier for this study.
        name: A short, human-readable name (also used as the scenario
            ID/name prefix for any scenarios generated from
            ``parameters``).
        base_project: The unmodified base project every scenario
            overrides.
        parameters: Parameters to sweep (Cartesian product if more than
            one); may be empty if ``scenarios`` alone defines the study.
        scenarios: Explicit, hand-defined scenarios to run in addition
            to any generated from ``parameters``; may be empty if
            ``parameters`` alone defines the study.
        max_scenarios: The ceiling on the *total* scenario count
            (explicit plus generated) this study may execute -- checked
            before any scenario runs; see
            :data:`~femtoolkit.studies.parameter_sweep.DEFAULT_MAX_SCENARIOS`.
    """

    study_id: str
    name: str
    base_project: Project
    parameters: list[ParameterDefinition] = field(default_factory=list)
    scenarios: list[Scenario] = field(default_factory=list)
    max_scenarios: int = DEFAULT_MAX_SCENARIOS


class StudyRunner:
    """Generates, validates, and executes a :class:`SimulationStudy` sequentially."""

    def __init__(self, run_manager: SimulationRunManager | None = None) -> None:
        self._run_manager = run_manager or SimulationRunManager()

    def run(self, study: SimulationStudy) -> StudyResult:
        """Execute every scenario in ``study`` and collect the results.

        Args:
            study: The study to run.

        Returns:
            A :class:`~femtoolkit.studies.results.StudyResult` holding
            every scenario and the run it produced, in execution order.

        Raises:
            StudySizeExceededError: If the total scenario count
                (explicit plus generated) exceeds ``study.max_scenarios``.
                No scenario is executed in this case.
            DuplicateScenarioIdError: If any two scenarios (explicit or
                generated) share a ``scenario_id``.
            ValidationError: If a scenario's override path is invalid.
        """
        scenarios = list(study.scenarios)
        if study.parameters:
            scenarios = scenarios + _generate_scenarios(
                study.name, study.parameters, max_scenarios=study.max_scenarios
            )

        if len(scenarios) > study.max_scenarios:
            raise StudySizeExceededError(
                f"Study {study.name!r} would execute {len(scenarios)} scenarios "
                f"({len(study.scenarios)} explicit + "
                f"{len(scenarios) - len(study.scenarios)} generated), which exceeds "
                f"max_scenarios={study.max_scenarios}. Reduce the number of explicit "
                "scenarios or swept parameter values, or raise max_scenarios if this "
                "many scenarios is intentional."
            )

        validate_unique_scenario_ids(scenarios)

        runs = []
        for scenario in scenarios:
            project = apply_scenario(study.base_project, scenario)
            runs.append(self._run_manager.execute(project, scenario_id=scenario.scenario_id))

        return StudyResult(
            study_id=study.study_id,
            study_name=study.name,
            base_project_id=study.base_project.project_id,
            parameters=list(study.parameters),
            scenarios=scenarios,
            runs=runs,
        )
