"""Custom exception types shared across the Finite Element Toolkit domain model."""

from femtoolkit.exceptions.exceptions import (
    ConstitutiveUpdateError,
    DegenerateElementError,
    DuplicateIDError,
    DuplicateNodeCoordinatesError,
    EigenvalueComputationError,
    EntityNotFoundError,
    FiniteElementToolkitError,
    InsufficientConstraintsError,
    InvalidAnalysisError,
    InvalidDeformationGradientError,
    InvalidElementConnectivityError,
    InvalidElementError,
    InvalidMaterialStateError,
    InvalidMeshError,
    InvalidSolverConfigurationError,
    NonlinearConvergenceError,
    SingularSystemError,
    SolverConvergenceError,
    SolverError,
    UnsupportedLoadingPathError,
    UnsupportedQualityMetricError,
    UnsupportedRefinementError,
    UnsupportedSolverError,
    ValidationError,
)

__all__ = [
    "ConstitutiveUpdateError",
    "DegenerateElementError",
    "DuplicateIDError",
    "DuplicateNodeCoordinatesError",
    "EigenvalueComputationError",
    "EntityNotFoundError",
    "FiniteElementToolkitError",
    "InsufficientConstraintsError",
    "InvalidAnalysisError",
    "InvalidDeformationGradientError",
    "InvalidElementConnectivityError",
    "InvalidElementError",
    "InvalidMaterialStateError",
    "InvalidMeshError",
    "InvalidSolverConfigurationError",
    "NonlinearConvergenceError",
    "SingularSystemError",
    "SolverConvergenceError",
    "SolverError",
    "UnsupportedLoadingPathError",
    "UnsupportedQualityMetricError",
    "UnsupportedRefinementError",
    "UnsupportedSolverError",
    "ValidationError",
]
